config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  root to: 'homes#top'
  get "/about", to: "homes#about"

  scope module: :public do
    patch '/users/:id/withdraw', to: 'users#withdraw', as: "withdraw"
    resources :users, except: [:new, :create]
    resources :schedules, only: [:create, :update, :destroy]
    resources :groups, except: [:new] do
      resource :group_users, only: [:create, :destroy]
      resources :chats, only: [:create]
      resources :group_schedules, only: [:create, :update, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  validates :message, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :group_users
  has_many :users, through: :group_users
  has_many :group_schedules, dependent: :destroy
  has_many :chat

  validates :name, presence: true

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

end

app/models/group_schedule.rb
class GroupSchedule < ApplicationRecord
  belongs_to :group
  
  validates :title, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :chats
  has_many :schedules, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image-user.png')
      profile_image.attach(io: File.open(file_path), filename: 'no-image-user.png', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_schedules_helper.rb
module GroupSchedulesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<div class="container-fluid content">
    <div class="calendar">
      <div class="month">
        <i class="prev"><</i>
        <div class="date">
          <h1></h1>
          <p></p>
        </div>
        <i class="next">></i>
      </div>
      <div class="weekdays">
        <div>Sun</div>
        <div>Mon</div>
        <div>Tue</div>
        <div>Wed</div>
        <div>Thu</div>
        <div>Fri</div>
        <div>Sat</div>
      </div>
      <div class="days"></div>
    </div>
</div>

<%= javascript_pack_tag 'calendar' %>

app/views/layouts/_not_sign_in.html.erb
<div class="header_inner">
  <div class="logo">
    <%= link_to "Paprikash", root_path, class:"logo_item" %>
  </div>
  <nav>
    <%= link_to "Sign in", new_user_session_path, class:"nav_item" %>
    <%= link_to "Sign up", new_user_registration_path, class:"nav_item" %>
    <%= link_to 'ゲストログイン（閲覧用）', public_guest_sign_in_path, method: :post, class:"nav_item" %>
  </nav>
</div>

app/views/layouts/_signed_in.html.erb
<div class="header_inner">
  <div class="logo">
    <%= link_to "Paprikash", root_path, class:"logo_item" %>
  </div>
  <nav>
    <%= link_to user_path(current_user), class:"signed_in_nav_item" do %>
      <i class="fas fa-user-alt"></i>
      My Page
    <% end %>

    <%= link_to groups_path, class:"signed_in_nav_item" do %>
      <i class="fas fa-users"></i>
      Groups
    <% end %>

    <%= link_to users_path, class:"signed_in_nav_item" do %>
      <i class="fas fa-user-friends"></i>
      Find Friends
    <% end %>

    <%= link_to destroy_user_session_path, method: :delete, class:"signed_in_nav_item" do %>
      Log out
      <i class="fas fa-sign-out-alt"></i>
    <% end %>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paprikash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= render 'layouts/signed_in' %>
      <% else %>
        <%= render 'layouts/not_sign_in' %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>